pipeline {
    agent any
    environment {
        CI = true
    }
        stages {
            stage('WhereamI') {
                steps {
                    sh 'pwd'
                    sh 'ls'
                }
            }
            stage('Install dependencies') {
                steps {
                    dir('get-your-way-frontend') {
                        sh 'ls'
                        sh 'pwd'
                        sh 'npm install'
                        sh 'npm audit fix'
                        sh 'npm run build'
                    }
                }

            }
            stage('Serving') {
                steps {
                    dir('get-your-way-frontend') {
                        sh 'serve -s build'
                    }
                }
            }

        }
}