pipeline {
    agent any
    environment {
        CI = true
    }
    stages {
        stage('Build') {
            steps {
                dir('get-your-way-frontend') {
                    sh """
                    npm install
                    npm audit fix
                    npm run build
                    """
                }
            }
        }
        stage('Deploy') {
            steps {
                sh """
                npm --prefix /get-your-way-front-end run build
                sudo rm -rf /var/www/jenkins-react-app
                sudo cp -r ${WORKSPACE}/get-your-way-front-end/build/ /var/www/jenkins-react-app/
                """
            }
        }
    }
}