pipeline {
    agent any
    environment {
        CI = true
    }
    stages {
        stage('Build') {
            steps {
                dir('get-your-way-frontend') {
                    sh """
                    npm install
                    npm audit fix
                    npm run build
                    ls
                    pwd
                    """
                }
            }
        }
        stage('Deploy') {
            steps {
                dir ('get-your-way-frontend') {
                    sh """
                    ls
                    pwd
                    npm run build
                    sudo rm -rf /var/www/jenkins-react-app
                    sudo cp -r ${WORKSPACE}/get-your-way-front-end/build/ /var/www/jenkins-react-app/
                    """
                }
            }
        }
    }
}